config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  # defaults to dashboard
  root :to => 'dashboard#dashboard_v1'
  
  # view routes
  get '/widgets' => 'widgets#index'
  get '/documentation' => 'documentation#index'

  resources :analytics do
    collection do
      get 'schools'
    end
  end

  resources :hackers do
    member do
      get 'favorite'
    end
    collection do
      get 'favorites'
    end
  end

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    delete "/logout" => "devise/sessions#destroy"
  end

  get 'dashboard/dashboard_v1'
  get 'dashboard/dashboard_v2'
  get 'dashboard/dashboard_v3'
  get 'dashboard/dashboard_h'
  get 'elements/button'
  get 'elements/notification'
  get 'elements/spinner'
  get 'elements/animation'
  get 'elements/dropdown'
  get 'elements/nestable'
  get 'elements/sortable'
  get 'elements/panel'
  get 'elements/portlet'
  get 'elements/grid'
  get 'elements/gridmasonry'
  get 'elements/typography'
  get 'elements/fonticons'
  get 'elements/weathericons'
  get 'elements/colors'
  get 'elements/buttons'
  get 'elements/notifications'
  get 'elements/carousel'
  get 'elements/tour'
  get 'elements/sweetalert'
  get 'forms/standard'
  get 'forms/extended'
  get 'forms/validation'
  get 'forms/wizard'
  get 'forms/upload'
  get 'forms/xeditable'
  get 'forms/imgcrop'
  get 'multilevel/level1'
  get 'multilevel/level3'
  get 'charts/flot'
  get 'charts/radial'
  get 'charts/chartjs'
  get 'charts/chartist'
  get 'charts/morris'
  get 'charts/rickshaw'
  get 'tables/standard'
  get 'tables/extended'
  get 'tables/datatable'
  get 'tables/jqgrid'
  get 'maps/google'
  get 'maps/vector'
  get 'extras/mailbox'
  get 'extras/timeline'
  get 'extras/calendar'
  get 'extras/invoice'
  get 'extras/search'
  get 'extras/todo'
  get 'extras/profile'
  get 'blog/blog'
  get 'blog/blog_post'
  get 'blog/blog_articles'
  get 'blog/blog_article_view'
  get 'ecommerce/ecommerce_orders'
  get 'ecommerce/ecommerce_order_view'
  get 'ecommerce/ecommerce_products'
  get 'ecommerce/ecommerce_product_view'
  get 'forum/forum_categories'
  get 'forum/forum_topics'
  get 'forum/forum_discussion'
  get 'pages/login'
  get 'pages/register'
  get 'pages/recover'
  get 'pages/lock'
  get 'pages/template'
  get 'pages/notfound'

  # api routes
  get '/api/documentation' => 'api#documentation'
  get '/api/datatable' => 'api#datatable'
  get '/api/jqgrid' => 'api#jqgrid'
  get '/api/jqgridtree' => 'api#jqgridtree'
  get '/api/i18n/:locale' => 'api#i18n'
  post '/api/xeditable' => 'api#xeditable'
  get '/api/xeditable-groups' => 'api#xeditablegroups'



  # the rest goes to root
  # get '*path' => redirect('/')
end

app/models/account.rb
class Account < ActiveRecord::Base
	has_many :users
	
end

app/models/analytics.rb
class Analytics < ActiveRecord::Base

	def top_schools
		[get_sum(self.schools_stats), self.schools_stats.slice(0..5)]
	end

	def add_languages(languages)
		puts languages
		if self.github_stats.nil?
			self.github_stats = {}
		end
		languages.each do |key, val|
			key.each do |k, v|
				puts " #{k} : #{v}"
				if self.github_stats.has_key?(k)
					self.github_stats[k] = self.github_stats[k] + v
				else
					self.github_stats[k] = v
				end
			end
			

		end
	end

private
	def get_sum(schools)
		return schools.collect { |x| x[1]}.reduce(:+)
	end
end

app/models/decision.rb
module Decision
	CONSTANTS = {'APPROVE' => 'Approved', 'REJECT' => "Rejected", 'WAITLIST' => "Waitlisted",
				'CONFIRM' => "Confirmed", 'DECLINE' => "Declined"}
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
end

app/models/favorite_hacker.rb
class FavoriteHacker < ActiveRecord::Base
	belongs_to :hacker
	belongs_to :user
end

app/models/hacker.rb
class Hacker < ActiveRecord::Base
	has_one :status, dependent: :destroy
	has_one :stat
	after_create :create_status, :create_stat
	before_update :send_decision

	has_many :favorite_hackers
	has_many :favorited_by, through: :favorite_hackers, source: :user

	def 

	def approve
		@status = self.status
		@status.update_attribute(:status, Decision::CONSTANTS['APPROVE'])
		generate_invitation(status)
		decision_made(status)
	end

	def generate_invitation(status)
		status.update_attribute(:invitation_key, SecureRandom.uuid)
		status.update_attribute(:invitation_sent_at, Time.now)

	end

	def reject
		@status = self.status
		@status.update_attribute(:status, Decision::CONSTANTS['REJECT'])
		decision_made(status)
	end

	def waitlist
		@status = self.status
		@status.update_attribute(:status, Decision::CONSTANTS['WAITLIST'])
		decision_made(status)

	end


	def create_status
		self.status = Status.new
	end

	def create_stat
		self.stat = Stat.new
	end

	def send_decision
		if self.status.status_changed? && self.status.status == Decision::CONSTANTS['APPROVE']
			self.status.invitation_sent_at = Time.now
		end
	end

	def logger
		@logger ||= Logger.new("#{Rails.root}/log/hacker.log")
	end

	def decision_made(status)
		status.update_attribute(:decision_made_at, Time.now)
		@hacker = Hacker.find(status.hacker_id)
		logger.info("hacker [#{@hacker.id}] -- #{@hacker.email} has been #{status.status}")
	end

	
	
end

app/models/stat.rb
class Stat < ActiveRecord::Base
	belongs_to :hacker
end

app/models/status.rb
class Status < ActiveRecord::Base
	belongs_to :hacker


	def confirm
		self.update_attribute(:decision => Decision::CONSTANTS['CONFIRM'])
	end

	def decline
		self.update_attribute(:decision => Decision::CONSTANTS['DECLINE'])
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :account, :inverse_of => :users
  has_many :favorite_hackers
  has_many :favorites, through: :favorite_hackers, source: :hacker
end

app/controllers/hackers_controller.rb
class HackersController < ApplicationController

	before_filter :authenticate_user!


	def index
	end

	def show
	  @hacker = Hacker.find(params[:id])
	  @pdf = ""
	end

	def favorite
	 	type = params[:type]
	 	@hacker = Hacker.find(params[:id])
	 	if type == "favorite"
	 		current_user.favorites << @hacker
	 		redirect_to :back, notice: "You favorited #{@hacker.first_name} #{@hacker.last_name}"
	 	elsif type = "unfavorite"
	 		current_user.favorites.delete(@hacker)
	 		redirect_to :back, notice: "#{@hacker.first_name} #{@hacker.last_name} unfavorited"
	 	else
	 		redirect_to :back, notice: "Something went wrong"
	 	end
	end

	def favorites
		@favorites = current_user.favorites
	end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/analytics_helper.rb
module AnalyticsHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper

	def render_hireable_pretty(bool)
		if bool
			return '<button type="button" class="btn btn-oval btn-success btn-xs">Yes</button>'
		end
		return '<button type="button" class="btn btn-oval btn-default btn-xs">No</button>'
	end
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/helpers/extras_helper.rb
module ExtrasHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/helpers/hacker_helper.rb
module HackerHelper
	require 'net/http'

	def external_profile_link_is_valid(profile_link)
		if ["http://", ""].include?(profile_link.strip)
			return false
		end
		return true 
	end

	def is_favorited_by_current_user?(hacker)
		return current_user.favorites.include?(hacker)
	end

end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/multilevel_helper.rb
module MultilevelHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/hackers/_external_profile_bar.html.erb
<div class="panel-body bg-inverse">
   <div class="row row-table text-center">
     <% if external_profile_link_is_valid(@hacker.github) %>
      <div class="col-xs-3">
         <%= link_to '<em class="fa fa-github fa-2x"></em><p class="m0 text-muted">Github</p>'.html_safe, @hacker.github, {:style => "text-decoration:none"} %>
      </div> 
     <% end %>
     <% if external_profile_link_is_valid(@hacker.github) %>
      <div class="col-xs-3">
         <%= link_to '<em class="fa fa-linkedin fa-2x"></em><p class="m0 text-muted">Linkedin</p>'.html_safe, @hacker.linkedin %>
      </div>
      <% end %>
      <% if !@hacker.resume.nil? %>
      <div class="col-xs-3">
         <%= link_to '<em class="fa fa-file-text-o fa-2x"></em><p class="m0 text-muted">Resume</p>'.html_safe, @hacker.resume %>
      </div>
      <% end %>
   </div>
</div>

app/views/hackers/_interests_learn.html.erb
   <div class="panel widget">
         <div class="row row-table row-flush">
            <div class="col-xs-4 bg-info text-center">
               <h4>Interests</h4>
            </div>
            <div class="col-xs-8">
               <div class="panel-body text-center">
                  <p><%= @hacker.experience %></p>
               </div>
            </div>
         </div>
     </div>
     <div class="panel widget">
         <div class="row row-table row-flush">
            <div class="col-xs-4 bg-success text-center">
               <h4>Wants to Learn</h4>
            </div>
            <div class="col-xs-8">
               <div class="panel-body text-center">
                  <p><%= @hacker.learn %></p>
               </div>
            </div>
         </div>
     </div>

app/views/hackers/_profile_card.html.erb
      <div class="panel widget">
         <div class="col-xs-0 pull-right" style="padding: 10px">
         <% if is_favorited_by_current_user?(@hacker) %>
          <%= link_to '<em class="fa fa-star fa-3x" style="color: orange"></em>'.html_safe, favorite_hacker_path(@hacker, type: "unfavorite"), method: "put", remote: true %>
        <% else %>
          <%= link_to '<em class="fa fa-star-o fa-3x" style="color: orange"></em>'.html_safe, favorite_hacker_path(@hacker, type: "favorite"), method: "put", remote: true %>
        <% end %>

         </div>

         <div class="panel-body">
            <div class="row row-table">
               <div class="col-xs-2 text-center">
               <% if @hacker.avatar.nil? %>
                  <img src="https://github.com/identicons/jasonlong.png" alt="Image" class="img-circle thumb96" />
               <% else %>
                  <img src=<%= image_url(@hacker.avatar) %> alt="Image" class="img-circle thumb96" />
               <% end %>
               </div>
               <div class="col-xs-4">
                  <h3 class="mt0"><%= "#{@hacker.first_name} #{@hacker.last_name}" %> 

                  </h3>
                  <ul class="list-unstyled">
                     <li class="mb-sm">
                        <em class="fa fa-certificate fa-fw"></em><%= "Studying #{@hacker.major} "%></li>
                     <li class="mb-sm">
                        <em class="fa fa-map-marker fa-fw"></em><%= @hacker.school %></li>
                     <li class="mb-sm">
                        <em class="fa fa-calendar fa-fw"></em><%= "Class of #{@hacker.graduation_date}" %></li>
                     <li class="mb-sm">
                        <em class="fa fa-envelope fa-fw"></em><%= @hacker.email %></li>
                  </ul>
               </div>
               <div class="col-xs-5">
                        <div role="tabpanel">
                           <!-- Nav tabs-->
                           <ul role="tablist" class="nav nav-tabs">
                              <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Interests</a>
                              </li>
                              <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Wants to Learn</a>
                              </li>
                           </ul>
                           <!-- Tab panes-->
                           <div class="bottom-aligned-text tab-content">
                              <div id="home" role="tabpanel" class="tab-pane active"><p><%= @hacker.experience.join(", ") %></p></div>
                              <div id="profile" role="tabpanel" class="tab-pane"><p><%= @hacker.learn.join(", ") %></p></div>

                           </div>
                        </div>
                     </div>
                  </div>
               </div>
               <%= render 'external_profile_bar' %>
         </div>

app/views/hackers/favorites.html.erb
<h3>Favorites
</h3>
<div class="row">

   <% @favorites.each do |hacker| %>
   <div class="col-xs-6">
   <%= render 'profile_card', :@hacker => hacker %>
   </div>
   <% end %>
</div>

app/views/hackers/show.html.erb
<%= link_to "< Back", root_path %><h3>Hacker Profile
</h3>
<% flash.each do |name, msg| %>
   
   <div role="alert" class="alert alert-warning">
   <%= msg %>
   </div>
   
<% end %>
<div class="row">
   <div class="col-lg-12">
            <%= render 'profile_card' %>
     </div>
   </div>
   <div class="container-fluid">
      <div class="row-fluid">
         <div class="span12">
            <div class="well well-sm" style="max-width: 840px">
               <img src=<%= image_path("resumes/#{@hacker.id}.svg") %> />
            </div>
         </div>
      </div>
   </div>
</div>
</div>
	